#!/bin/bash

#
# Copyright © 2021 92AK
#

JARPATH=$1
MOD=$2
ROOT_DIR=$PWD

# copy original jar into place
mkdir -p $ROOT_DIR/out
cp $ROOT_DIR/$JARPATH $ROOT_DIR/out/$MOD.jar

# extract original jar
rm -rf classes
mkdir classes
cd classes
jar xf $ROOT_DIR/$JARPATH

# compile module-info.java (generated by gen.sh)
cd $ROOT_DIR/work/$MOD
javac -cp $ROOT_DIR/mods --module-path $ROOT_DIR/mods -d $ROOT_DIR/classes module-info.java

# update output jar
mkdir $ROOT_DIR/newmods
jar uf $ROOT_DIR/out/$MOD.jar -C $ROOT_DIR/classes module-info.class
cp $ROOT_DIR/out/$MOD.jar $ROOT_DIR/newmods/$MOD.jar
cp $ROOT_DIR/newmods/$MOD.jar $ROOT_DIR/mods/$MOD.jar

cd $ROOT_DIR
rm $ROOT_DIR/$JARPATH
echo "Ready."
